version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: mysql_root_pass
    volumes:
      - ./data/mysql:/var/lib/mysql

  wordpress:
    image: wordpress:php8.0-fpm
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./data/html:/var/www/html
    links:
      - db
    
  nginx:
    image: nginx:1.21.3-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports:
      - 9000:80
    links:
      - wordpress